### ISSUE TITLE
Enable Debugging in kyt (Node Debugger in Chrome Dev tools)

### ISSUE THREAD

**Issue by jkosturko** [NYTimes/kyt#113]
I am looking for a way to run --debug=true with docker for project-vi.   

Here is how to run the debugger that I would like to run: 
https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27#.elnqyj305

**Comment by gontard** [comment]
@delambo  I use `kyt dev -- --inspect`, and it works.

I have just a small issue. The souce map is detected by chrome-dev-tools, but my server files are not mapped (i saw only a big `server/main.js` file), only node_modules are mapped.

![capture d ecran 2016-11-02 a 15 06 21](https://cloud.githubusercontent.com/assets/1221664/19931804/245ec4c6-a10e-11e6-89c4-8fc5057e9e9f.png)

Any ideas ?

**Comment by delambo** [comment]
@gontard - Can you open an issue? Thanks!

**Comment by gontard** [comment]
@delambo done: https://github.com/NYTimes/kyt/issues/319
