### ISSUE TITLE
Refactor how Babel configuration is loaded in

### ISSUE THREAD

**Issue by tizmagik** [NYTimes/kyt#134]
This came up as part of the work on #115 . Right now, the way the Babel config is loaded for Jest is by running the `modifyWebpackConfig()` callback and grabbing it from there, but this overloads that method a bit. Now that there are 2 consumers for the Babel configuration (Webpack and Jest), it would be cleaner to pull that out.

Here's how it could work:
- Userland can optionally define a `.babelrc` file if they have any custom plugins or presets that they would like to use. (We should also check `package.json` for the configuration.)
- We'll respect the `BABEL_ENV` setting to pull in the appropriate dev/prod/test babel configuration.
- Merge it in with kyt's base babel configuration.

For most use cases, a separate babelrc file in userland won't be needed, but in the cases where it is, it will be easier to configure than having to do so programmatically in the `modifyWebpackConfig()` callback which requires sniffing for the `babel-loader`.

**Comment by delambo** [comment]
@tizmagik - I'm a little worried about the "merge" step. At one point, I remember talking about a `modifyBabelConfig` kyt.config callback that would work similarly to the other modify callbacks. I kind of like that idea. What do you think about supporting that instead of your proposal?

**Comment by tizmagik** [comment]
Yea, that would probably work too. My concern though would be around users having to 'learn' this kyt-flavored API instead of relying on Babel's semantics (well, Babel's semantics + some kyt magic to merge in some base configuration, to be fair).

I think in general it might make sense for us to move away from the `modify*()` pattern, and instead rely on static configuration merging. For example, Webpack 2 has added support for multiple configs, and depending on how that works in practice, it _may_ obviate the need for the `modifyWebpackConfig()` callback -- too early to tell though.

That's for a larger discussion though and I think either solution is better than the current state where we're piggy-backing off of `modifyWebpackConfig()`.

**Comment by delambo** [comment]
The one thing I worry about when merging a user .babelrc is that the user doesn't have control to override, just merge. Let's implement the `modifyBabelConfig` for now. Much like the `modifyWebpackConfig`, we'll run the config we derive in [babel.js](https://github.com/NYTimes/kyt/blob/master/config/babel.js) through a client supplied callback, `modifyBabelConfig`, defined in kyt.config.js.

**Comment by jaredmcdonald** [comment]
I'll take a crack at this one, if that's cool!

**Comment by delambo** [comment]
Cool!

**Comment by tizmagik** [comment]
Go for it! Remember to have it respect `BABEL_ENV` if set.

**Comment by delambo** [comment]
I think we're close to wrapping up the `modifyBabelConfig` function in #235. The original proposal was to support merging a user's .babelrc into kyt's configuration. Instead of merging, what if we support a user .babelrc file that would work as an override?

I actually have a use case for this right now in a starter kyt that I'm building where the framework that I'm using has an additional loader that requires a .babelrc. I worked around it pretty easily by including a .babelrc and assigning it to the babel loader in the `modifyWebpackConfig`. Maybe that's a good enough solution, but would like your thoughts...

**Comment by tizmagik** [comment]
The issue with allowing a .babelrc that would do a full-on override is that it would require some of the internal babel configuration details of kyt which seems like a lot of overhead and easy to get wrong in userland.

> I worked around it pretty easily by including a .babelrc and assigning it to the babel loader in the modifyWebpackConfig

I think that's a good solution, and we can note that as a "recipe" in the docs.

**Comment by jaredmcdonald** [comment]
closing in favor of #322
