### ISSUE TITLE
Pass through command flags that kyt doesn't use

### ISSUE THREAD

**Issue by ccpricenytimes** [NYTimes/kyt#150]
We want to support other flags that kyt isn't using so developers can pass down command line options to tools we use. 

Example of use case here https://github.com/NYTimes/kyt/commit/d2e2ad878b3ee6ed32552ddf41251f266ab3cbf4#commitcomment-18973379

**Comment by tizmagik** [comment]
Here's an example of how this can be done, but specific to one command, `test`, it would be good to generalize this solution: 

https://github.com/NYTimes/kyt/blob/feature/jest/cli/actions/test.js#L17 with
https://github.com/NYTimes/kyt/blob/feature/jest/cli/actions/test.js#L30
