### ISSUE TITLE
E2E tests for kyt

### ISSUE THREAD

**Issue by ccpricenytimes** [NYTimes/kyt#162]
After Jest is complete, we should revisit end to end testing.

Things we should test:

1) Server is healthy after hot reloading
2) Build commands create correct assets
3) environment variables are respected
4) setup creates correct environment with and without starter kyts

**Comment by tizmagik** [comment]
Can we refactor the work you did in #90 ?

**Comment by ccpricenytimes** [comment]
It's possible. Not sure how much would work in Travis.

**Comment by tizmagik** [comment]
For Travis we could run the test in a working/temp directory, it should work fine. I believe CRA does similar: https://github.com/facebookincubator/create-react-app/blob/master/tasks/e2e.sh#L115

**Comment by tizmagik** [comment]
Also maybe this [codemod](https://gist.github.com/dcousineau/0170c4cf30bcc83ebf1a39b4636ae7d6) as [mentioned here](https://twitter.com/dcousineau/status/776506074383998978) would be useful too!
