### ISSUE TITLE
Lodash imports

### ISSUE THREAD

**Issue by pedroputz** [NYTimes/kyt#163]
As we did to `react-router`, `lodash` gives us the possibility of reducing the final bundle size importing just the needed functions:

Instead of:
```js
import _ from 'lodash';

const something = _.uniqueId();
```

We can do:
```js
import uniqueId from 'lodash/utility/uniqueId';

const something = uniqueId();
```

Today we use `lodash` on plans page and linter tools, the second one doesn't affect build size.

**Comment by tizmagik** [comment]
Thanks for the issue @pedroputz -- this is good to keep in mind, although we are not using `lodash` in kyt. Am I missing something?

**Comment by pedroputz** [comment]
@tizmagik Hey, sorry for this. I pressed the issue tab without realizing that I wasn't on the correct browser tab 😞 . I knew that someday a browser with a lot of open tabs would be a problem.
