### ISSUE TITLE
react/require-extension is deprecated

### ISSUE THREAD

**Issue by tizmagik** [NYTimes/kyt#164]
```
The react/require-extension rule is deprecated. Please use the import/extensions rule from eslint-plugin-import instead.
```

**Comment by cwonrails** [comment]
This is an upstream issue with `eslint-plugin-import`. A temporary solution was posted [here]:(https://github.com/airbnb/javascript/issues/978#issuecomment-244611697).

I'd be glad to put in a PR. I've also updated the outdated deps in `package.json` in my fork, but I can make a clean branch with this change alone.

**Comment by ccpricenytimes** [comment]
A PR with the change would be awesome @cwonrails Thanks!

**Comment by cwonrails** [comment]
No problem at all! Incoming now 👍

**Comment by tizmagik** [comment]
Hmm, well we wouldn't want to 'lose' out on this rule necessarily. It's still useful even if it's deprecated. That workaround seems to suggest to disable the rule just to remove the warning that gets logged. I'm not sure that makes sense. Thoughts?

**Comment by cwonrails** [comment]
Understood. The workaround is to turn it off for _that_ error while also adding the non-deprecated one.

**Comment by tizmagik** [comment]
Ah, gotcha, that sounds good then! 👍  Thanks!

**Comment by cwonrails** [comment]
Of course! PR here: https://github.com/NYTimes/kyt/pull/165
