### ISSUE TITLE
Update .eslintrc to .eslintrc.json

### ISSUE THREAD

**Issue by ccpricenytimes** [NYTimes/kyt#166]
.eslintrc is deprecated :( 

We should do several things. 

1) support all eslint config file types http://eslint.org/docs/user-guide/configuring#configuration-file-formats
2) on setup the file copied should be .eslintrc.json

**Comment by tizmagik** [comment]
Can we loop this in to #91 also?

**Comment by ccpricenytimes** [comment]
I'd like to get a quick fix in for this so let's keep them separate.
