### ISSUE TITLE
Group linting commands in `kyt lint`

### ISSUE THREAD

**Issue by delambo** [NYTimes/kyt#208]
Should we group the scripts and stylesheet linting commands into `kyt lint`? I'm proposing the following linting commands:

`kyt lint-script` - lints scripts (name?)
`kyt lint-style` - lints stylesheets
`kyt lint` - lints scripts and stylesheets

**Comment by ccpricenytimes** [comment]
maybe `lint-js` ?
Otherwise 👍

**Comment by kytwb** [comment]
I see there's already these commands:
```
kyt lint 
kyt lint-style
```
Goal here is to rename `lint` to `lint-js` then create a `lint` that both run `lint-js` and `lint-style`?
By the way, I prefer `lint-script` with `lint-style`, or `lint-js` with `lint-css`.
Let me know if I got it right and I'll do it.
