### ISSUE TITLE
Re-enable source maps in dev

### ISSUE THREAD

**Issue by tizmagik** [NYTimes/kyt#219]
Not sure when this started happening but currently the source-maps are not working at least in dev mode. For a production build, source maps are being emitted.

We should also probably use `devtool: 'cheap-module-eval-source-map'` or similar in dev.

**Comment by leshow** [comment]
I'll grab this. it looks like the webpack.dev.client.js is not set up to use source-maps

**Comment by leshow** [comment]
Is there documentation for how to test my changes? Running setup from a different dir complains about "working best when you execute commands from the root of your project"

**Comment by tizmagik** [comment]
That's because kyt expects to see a `package.json` so if you `npm init` in an empty directory and then run setup it should work.

**Comment by delambo** [comment]
The way I test locally is by running `npm link` in my locally cloned `kyt`. Then in other projects I can run kyt globally - `kyt <command>`.
