### ISSUE TITLE
Docs: Note to use --no-cache when changing Jest-affecting configuration

### ISSUE THREAD

**Issue by gontard** [NYTimes/kyt#221]
Hello,
I have added the babel stage-2 preset in the kyt.config.js file. 

```
...
modifyWebpackConfig: (baseConfig, options) => {
    const loaders = baseConfig.module.loaders;
    const babelLoader = loaders.find(loader => loader.loader === 'babel-loader');
    babelLoader.query.presets = ["babel-preset-react", ["babel-preset-latest", { "modules": false }], 'stage-2'];
  }
...
```

It works when i develop by launching `npm run dev`.
But the tests failed:

```
 FAIL  example.js
  ● Test suite failed to run

    /.../src/example.js:8
          const { promise, types, ...rest } = action;
                                  ^^^
    SyntaxError: Unexpected token ...

      at transformAndBuildScript (../node_modules/jest-runtime/build/transform.js:284:10)
      at Object.<anonymous> (example.test.js:2:51)
```

I though that jest preprocessor use the same babel configuration.

Any ideas ?

**Comment by tizmagik** [comment]
Hi @gontard thanks for the issue! 

Hmm, yea it should be using the same babel config... could you try running the test and passing along `--no-cache` to Jest?

```
kyt test -- --no-cache
```

**Comment by gontard** [comment]
It works
thanks @tizmagik !

For now, i have added --no-cache in the package.json. 

```
"scripts": {
  "dev": "kyt dev",
  "build": "kyt build",
  "start": "kyt start",
  "test": "kyt test -- --no-cache",
  "test-watch": "kyt test -- --watch --no-cache",
  "test-coverage": "kyt test -- --coverage --no-cache --",
  "lint": "kyt lint",
  "lint-style": "kyt lint-style",
  "proto": "kyt proto",
  "kyt:help": "kyt --help"
}
```

May be it should be the default.

Thanks again

**Comment by tizmagik** [comment]
Glad it's working!

`--no-cache` should only be needed whenever Jest configuration changes, I'd hesitate to include it in the script every time since it slows down the tests, but maybe we can add something to the docs to note this issue for users.

**Comment by gontard** [comment]
Ok. 
I didn't notice any performance issue but i haven't a lot of tests.

**Comment by ccpricenytimes** [comment]
Closing. Glad everything's working! 

Thanks @gontard and @tizmagik

**Comment by tizmagik** [comment]
Reopening. Let's note this in the docs as I'd expect for this to happen to many people.
