### ISSUE TITLE
Break up kyt into a multi-package mono-repo

### ISSUE THREAD

**Issue by delambo** [NYTimes/kyt#240]
I've been thinking about how to improve `setup`. It would probably be more useful/magical if it was a global command that created a project directory, setup a package.json and installed the given starter kyt. Maybe it should be broken out into its own package - `kyt-cli`? - so that it can be installed globally and it could do the job of installing the core of `kyt` locally. 

We could also break out the linters into packages. Maybe that's over-organizing.

Thoughts?

**Comment by delambo** [comment]
Core starter kyts could be moved in as packages too.

**Comment by tizmagik** [comment]
👍  

I think this would help with managing the core starter kyts (we still reference AVA in the default starter kit 😮 ). I also like the idea of a separate CLI, since it's sort of awkward to start a new project and have to `npm init && npm i -S kyt && kyt setup`.

**Comment by jaredmcdonald** [comment]
closing in favor of #323
