### ISSUE TITLE
Support Yarn

### ISSUE THREAD

**Issue by ccpricenytimes** [NYTimes/kyt#254]
https://github.com/yarnpkg/yarn

Two steps:
- [ ]  Test to make sure kyt works successfully when installed with yarn
- [ ] add yarn support for starter-kyts in setup. Should still support npm.

**Comment by dting** [comment]
I took a quick look using yarn with kyt. Seems like this [PR #809](https://github.com/yarnpkg/yarn/pull/809)  needs to go in before yarn can be used to run the scripts in package.json with any spaces. Using `npm run` does still work though.

The other issue is that using `npm link` in a development kyt repo and `npm link kyt` to link the local package for development doesn't seem to create the `.bin` folder in the `node_modules` folder of the package using the link.

**Comment by gendelbendel** [comment]
@dting As for your first point, I found a temporary workaround for [PR #809](https://github.com/yarnpkg/yarn/pull/809) until yarn 0.15.2 is released. You can refer to my PR [here](https://github.com/swarajgiri/express-bootstrap/pull/32) if you wanted to take a stab at it.

**Comment by ccpricenytimes** [comment]
Looks like the fix is in v0.16.0 

https://github.com/yarnpkg/yarn/releases/tag/v0.16.0
