### ISSUE TITLE
Enable css-module jest support

### ISSUE THREAD

**Issue by khalidsalomao** [NYTimes/kyt#257]
What do you thing about enabling react-css-module support in jest tests as described in [jest documetation](https://facebook.github.io/jest/docs/tutorial-webpack.html)?

Currently I need to customize jest configuration in `kyt.config.js`:

``` js
modifyJestConfig: (baseConfig) => {
    // solution for jest / enzime and css-module problem:
    baseConfig.moduleNameMapper['^[./a-zA-Z0-9$_-]+\\.(css|scss)$'] = 'identity-obj-proxy';
    return baseConfig;
}
```

And add the necessary dependencies:
`npm install identity-obj-proxy --save-dev`

**Comment by tizmagik** [comment]
Yes, a PR for this would be great! Currently this just lives as a "TODO" in the code (https://github.com/NYTimes/kyt/blob/master/utils/jest/style.stub.js#L1), but thank you for creating a proper issue @khalidsalomao ! 😄

**Comment by khalidsalomao** [comment]
@tizmagik :+1: 
I will take a look into it!

**Comment by delambo** [comment]
@khalidsalomao - Did you get a chance to check this out? I ran into this problem the other day when I tried to test against a class in an internal project. I'd really like to get a fix for this.

**Comment by khalidsalomao** [comment]
@delambo sorry I didn't check this out yet! I will look into it tomorrow!
As a temporary solution you could simply enable it in the `kyt.config.js` as described above.

**Comment by delambo** [comment]
@ccpricenytimes got this to work in a 0.4.0rc. It should land soon in a final 0.4.0 version.
