### ISSUE TITLE
Has anyone run into publickey issues before

### ISSUE THREAD

**Issue by jennylia** [NYTimes/kyt#268]
Hi All, 

I was just trying out kyt but I can't get it working at the setup command. 
There are some issues for permissions.
I'm not sure, has anyone run into this?
I've attached some logs.

Jennys-MacBook-Air:test_kyt jennylian$ node_modules/.bin/kyt setup
? Would you like to setup with the default starter-kyt? Yes
🔥  Setting up starter-kyt
Cloning into '/Users/jennylian/Desktop/play/hacktoberfest/test_kyt/.kyt-tmp'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

❌  There was a problem cloning the repository
Cloning into '/Users/jennylian/Desktop/play/hacktoberfest/test_kyt/.kyt-tmp'...
Warning: Permanently added the RSA host key for IP address '192.30.253.112' to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

❌  Failed to setup: git@github.com:NYTimes/kyt-starter.git
Jennys-MacBook-Air:test_kyt jennylian$ 
Jennys-MacBook-Air:test_kyt jennylian$ node_modules/.bin/kyt setup -r git@github.com:nytimes/kyt-starter-universal.git
🔥  Setting up starter-kyt
Cloning into '/Users/jennylian/Desktop/play/hacktoberfest/test_kyt/.kyt-tmp'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

❌  There was a problem cloning the repository
Cloning into '/Users/jennylian/Desktop/play/hacktoberfest/test_kyt/.kyt-tmp'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

❌  Failed to setup: git@github.com:nytimes/kyt-starter-universal.git
Jennys-MacBook-Air:test_kyt jennylian$

**Comment by ccpricenytimes** [comment]
Hi @jennylia sorry to hear it's not working for you. Do you have a github ssh key set up? The `setup` command currently only supports installing starter-kyts that way.

Here are some setup instructions. https://help.github.com/enterprise/11.10.340/user/articles/generating-ssh-keys/

**Comment by jennylia** [comment]
I think this is not an issue of me putting up my ssh keys on github through the setting page (because if it were, I wouldn't be able to push commits into repos on Github). I think this is something else.

**Comment by jaredmcdonald** [comment]
@jennylia - it's possible to push and pull from GH https remotes, so I'm not sure that rules anything out. give the public key a try and if that doesn't work I can try to dig deeper into what's going on 👍

**Comment by jennylia** [comment]
Hi @jaredmcdonald @ccpricenytimes, I was able to setup SSH public keys with another computer and it worked. Thanks. Closing this issue now.
