### ISSUE TITLE
default starter-kyt setup to https

### ISSUE THREAD

**Issue by jaredmcdonald** [NYTimes/kyt#274]
as pointed out in #268, the default starter kyt uses ssh to clone from GitHub, which will fail if the user (or CI server, etc) doesn't have a public key set up. since they're public, let's default to the https url (users are still free to specify repos over ssh with the `-r` flag)

**Comment by alexbenic** [comment]
I would like to fix this.

**Comment by jaredmcdonald** [comment]
@alexbenic - great, let me know if you have any questions!

**Comment by gkiely** [comment]
I just ran into this issue on mac so not sure if it's fixed.
`kyt setup -r https://github.com/NYTimes/kyt-starter-universal.git`
Fixed the issue.
