### ISSUE TITLE
Load plugin using babel-loader

### ISSUE THREAD

**Issue by paulthealien** [NYTimes/kyt#279]
Having issues loading [babel-plugin-import](https://www.npmjs.com/package/babel-plugin-import) using the ```modifyWebpackConfig``` function. It is a modular import library. I want to use it to import [antd](https://github.com/ant-design/ant-design) modules(like [so](https://ant.design/docs/react/practical-projects))

My ```kyt.config.js``` file. 

```javascript

// Base kyt config.
// Edit these properties to make changes.


modifyWebpackConfig: (baseConfig, options) => {
  /* *
  * Add Plugins 
  */
  
  const babelLoader = baseConfig.module.rules.find(loader => loader.loader === 'babel-loader');
  babelLoader.options.plugins.push(["import", { libraryName: "antd", style: "css" }]);
  
  return baseConfig;
}

module.exports = {
  reactHotLoader: true,
  debug: false,
};

```

**Comment by tizmagik** [comment]
Hey @paulthealien sorry you're having trouble! What is the error you get? Do you have a repo we could check out and reproduce the issue?

**Comment by paulthealien** [comment]
@tizmagik thanks for getting back. There's no error per se just that it isn't loading the compiled assets. 

Here's a screenshot
<img width="706" alt="screen shot 2016-10-26 at 10 00 59 pm" src="https://cloud.githubusercontent.com/assets/3650761/19752010/e608bc90-9bc7-11e6-9d67-ae275c967a05.png">

**Comment by tizmagik** [comment]
Without having a sample repo to check out, it's hard to say what's going on. But, if what you've pasted is your kyt.config.js file then it doesn't look quite right, make sure that your modifyWebpackConfig function is defined as part of module.exports:

```javascript
module.exports = {
  reactHotLoader: true,
  debug: false,
  modifyWebpackConfig: (baseConfig, options) => {
    const babelLoader = baseConfig.module.rules.find(loader => loader.loader === 'babel-loader');
    babelLoader.options.plugins.push(["import", { libraryName: "antd", style: "css" }]);
  
    return baseConfig;
  }
};
```

**Comment by paulthealien** [comment]
@tizmagik thank you that worked. I'll go ahead and close this. Awesome library by the way!

**Comment by strangerontheinternet** [comment]
@paulthealien - also wanted to note that we are evaluating some options to make babel configuration smoother, take a look at #250 and #134

**Comment by jaredmcdonald** [comment]
@paulthealien - also wanted to note that we are evaluating some options to make babel configuration smoother, take a look at #250 and #134
