### ISSUE TITLE
Update babel dependencies

### ISSUE THREAD

**Issue by delambo** [NYTimes/kyt#286]
It looks like the babel dependencies have been upgraded.

```
babel-cli    6.16.0  →        6.18.0
babel-core    6.17.0  →        6.18.0
babel-loader    6.2.5  →         6.2.7
babel-plugin-transform-react-remove-prop-types     0.2.9  →        0.2.10
```

Please check out the changelogs for these tools and make sure that there are not breaking changes that may affect kyt. Also, it would be nice to test this against the Universal starter kyt, along with the e2e and unit tests.

**Comment by PedroCSSilva** [comment]
@delambo
