### ISSUE TITLE
Replace default npm init test script on setup

### ISSUE THREAD

**Issue by delambo** [NYTimes/kyt#288]
On `npm init` a "test" script is added in the package.json scripts section. It looks like the following:

```
"test": "echo \"Error: no test specified\" && exit 1"
```

We should sniff this out [when we add scripts](https://github.com/NYTimes/kyt/blob/master/cli/actions/setup.js#L68) during our `setup` command and overwrite the script with our kyt test script: `kyt test`.

**Comment by aterranova-bv** [comment]
I'll tackle this one, happy hacktoberfest!  👻 🎃 👻 🎃

**Comment by jaredmcdonald** [comment]
addressed in #293, closing
