### ISSUE TITLE
Expand e2e tests

### ISSUE THREAD

**Issue by delambo** [NYTimes/kyt#296]
So far the e2e dev test includes checking the command line output and quickly testing the browser to see that the server is returning 200. It would be nice to test the restart process. Basically, after touching a src file, make sure the console output includes the restart log. I'm open to suggestions on how to better test this and more in the dev command!

**Comment by udnisap** [comment]
I would like to work on it. 
If I understand it correctly, what needs to be done is to add a test that checks the server tests and the console. Is it?

**Comment by delambo** [comment]
Sorry for the late reply @udnisap. Yes, a server restart triggers some console output which we should verify.
