### ISSUE TITLE
kyt.cmd doesn't work

### ISSUE THREAD

**Issue by conor909** [NYTimes/kyt#308]
after installing from `npm` and trying to open the `node_modules/.bin/kyt.cmd` a terminal window opens for a second and then closes again, so I cant run `kyt setup`.  I'v then tried running `kyt` from the project root but I get `kyt is not recognised...`.  Am I doing something wrong?

**Comment by jaredmcdonald** [comment]
hey @conor909! give `./node_modules/.bin/kyt.cmd setup` a try (running `kyt` by itself wouldn't work unless you manually added it to your `PATH`--there are plans to separate out a global CLI for setup in kyt 0.4.0ish, see #240).

you're using Windows, correct? if the above command doesn't work, might be an issue for #18

**Comment by oscar-g** [comment]
In my experience with Kyt on Windows, I just do `./node_modules/.bin/kyt <command>`, without the `.cmd`, and it works.  However, I am using `MINGW64` not `cmd.exe`.

**Comment by conor909** [comment]
So from the root folder I cannot type `./node_modules/.bin/kyt.cmd setup`, windows terminal complains the "." is not a recognised command.  So Iv been trying to go to the specific `.bin` folder by changing directory: `cd node_modules/.bin`.  If I then run `kyt.cmd` or just `kyt setup`, I get a message `❌  kyt works best when you execute commands from the root of your project where kyt is installed.`

**Comment by oscar-g** [comment]
@conor909 try this from the root of your project:

`node_modules\.bin\kyt.cmd dev`

Backslashes, instead of forward slashes

**Comment by conor909** [comment]
Ah, thanks @oscar-g this seems to work but then fails at cloning the repository, 
```
❌  There was a problem cloning the repository

Cloning into 'C:\Users\Conor\Documents\starter\.kyt-tmp'...
Host key verification failed.
fatal: Could not read from remote repository.
```
but that could be an new issue.

**Comment by oscar-g** [comment]
Yeah, it looks like a separate issue...maybe in your ssh config? Or a typo
in the repo URL?

**Comment by jaredmcdonald** [comment]
@conor909 - I think @oscar-g is right, try setting up your SSH key (documented [here](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/)). alternately, you can specify an HTTPS repository url with the `-r` flag (docs [here](https://github.com/NYTimes/kyt/blob/master/docs/commands.md#setup)).

also worth noting that the default setup url will be HTTPS instead of ssh in the next release of kyt, see #298

**Comment by jaredmcdonald** [comment]
going to close this for now since it seems like a separate issue, but please reopen if i'm wrong!
