### ISSUE TITLE
[question] use kyt with pm2

### ISSUE THREAD

**Issue by HaveF** [NYTimes/kyt#320]
Thanks for this project! I do like it❤️

I know in kyt, we start production version by `npm start`, `kyt start`,
what I can do to use  [PM2 - Advanced Node.js process manager](http://pm2.keymetrics.io/)?
```
pm2 start build/server/main.js
```
like this or?

Thanks for your work again!

**Comment by jaredmcdonald** [comment]
hey @HaveF, that looks about right! let us know if that doesn't work--feel free to reopen the issue if that's the case :)

**Comment by jaredmcdonald** [comment]
(also, just wanted to note you'll have to run `npm build`, aka `kyt build`, first to generate `build/server/main.js`)
