### ISSUE TITLE
[Feature request]copy devDependencies when use kyt setup from starter

### ISSUE THREAD

**Issue by HaveF** [NYTimes/kyt#327]
### Versions of kyt, node, OS
0.3.0

### Bug or Feature?
feature: copy devDependencies when `kyt setup`

### Current Behavior
ignore devDependencies field in starter's package.json

### Desired Behavior
copy devDependencies when `kyt setup`

I do find the cli setup part [kyt/setup.js at master · NYTimes/kyt](https://github.com/NYTimes/kyt/blob/master/cli/actions/setup.js#L59) only add dependencies from tempPackageJSON, but did nothing about `devDependencies`.

**Comment by jaredmcdonald** [comment]
seems like a good idea, maybe it should also copy over `peerDependencies` (and maybe even [`optionalDependencies`](https://docs.npmjs.com/files/package.json#optionaldependencies)) for completeness?

**Comment by ccpricenytimes** [comment]
I think we can wrap this into the monorepo work
