### ISSUE TITLE
Interrupting build doesn't stop

### ISSUE THREAD

**Issue by julianvmodesto** [NYTimes/kyt#328]
### Versions of kyt, node, OS
kyt 0.3.0
node 6.9.1
macOS 10.11.6

### Bug or Feature?
minor bug

### Current Behavior
It seems like interrupting `kyt build` won't stop the build, since i get the build output even after backing out with CTRL+C.

```
$ yarn run build
<CTRL+C>
^C
$ ls wherever
$ cd here
$ ...
👍  Client build successful
ℹ️  Assets: ...
👍  Server webpack configuration compiled
👍  Server build successful

✅  Done building
```

I happened to run and interrupt the build command twice, so I got the output twice later.

### Desired Behavior
Would be nice to have the build cancel entirely on interrupt

**Comment by jaredmcdonald** [comment]
👍 , I actually just saw this this morning too. think we just need to watch for a `SIGINT`
