### ISSUE TITLE
[help]how to test the server code?

### ISSUE THREAD

**Issue by HaveF** [NYTimes/kyt#329]
### Versions of kyt, node, OS
0.3.0

### Bug or Feature?
Feature

### Current Behavior
Don't know how to test the server code

[This issue](https://github.com/NYTimes/kyt-starter-universal/issues/19) is come from kyt-starter-universal repo:

I just export `src/server/index.js`s app, and write a dead simple test file to test server.

But failed like this after run `kyt test`:

```
  ● Test suite failed to run

    ReferenceError: KYT is not defined

      at Object.<anonymous> (server/server.js:13:28)
```
caused by this line in source code [kyt-starter-universal/index.js](https://github.com/NYTimes/kyt-starter-universal/blob/master/src/server/index.js#L13)
```js
const clientAssets = require(KYT.ASSETS_MANIFEST); // eslint-disable-line import/no-dynamic-require
```

This line is total fine when I run `kyt dev`, but failed at `kyt test`, I thought it must be  [kyt/test.js](https://github.com/NYTimes/kyt/blob/master/cli/actions/test.js) does not pass right env like [kyt/dev.js](https://github.com/NYTimes/kyt/blob/master/cli/actions/dev.js) does.
 
I also find `KYT` is defined in [kyt/webpack.base.js](https://github.com/NYTimes/kyt/blob/master/config/webpack.base.js#L33), but do not know how to fix.

@delambo advice me to set package.json as below:
```js
  "jest": {
    "globals": {
      "KYT": true
    }
  }
```
Console still complain: `ReferenceError: KYT is not defined`

Have any other idea I can try?

Thanks

**Comment by jaredmcdonald** [comment]
hey @HaveF, sorry for the delayed response! try adding it to the [`modifyJestConfig` callback](https://github.com/NYTimes/kyt/blob/master/docs/kytConfig.md#modifyjestconfig) in `kyt.config.js`

so, something like this:

```js
...
modifyJestConfig(baseConfig) {
  return Object.assign(baseConfig, {
    globals: {
      KYT: {} // your KYT object mock goes here
    },
  })
}
````

**Comment by HaveF** [comment]
@jaredmcdonald thanks for your response. It could fixed with your advice, and I modify `kyt.config.js` like this

```js
  modifyJestConfig:    (baseConfig) => {
    return Object.assign(baseConfig, {
      globals: {
        KYT: {
          PUBLIC_DIR:      'src/public',
          ASSETS_MANIFEST: '--PATH---TO----PROJECT/build/publicAssets.json'
        } // your KYT object mock goes here
      },
    })
  }
```
But  PUBLIC_DIR, and ASSETS_MANIFEST are default value of KYT, [kyt/index.js at master · NYTimes/kyt](https://github.com/NYTimes/kyt/blob/master/packages/starter-kyts/kyt-starter-universal/src/server/index.js#L13)

Maybe you can consider to add them as default JestConfig option.

Thanks!

**Comment by HaveF** [comment]
#335
