### ISSUE TITLE
KYT_SERVER_RENDER boolean

### ISSUE THREAD

**Issue by cameronroe** [NYTimes/kyt#331]
### Versions of kyt, node, OS
kyt: 0.3.0

### Bug or Feature?
Feature

### Current Behavior
Currently I don't see a way to check when the server render happens. It would be useful when using redux middleware that depends on the browser `window`. For example, redux dev tools gives you window.devToolsExtension from the Chrome Extension. 

### Desired Behavior
Ideally, I could check something like `KYT_SERVER_RENDER` to avoid using the `window` during the server render.

**Comment by aeldaly** [comment]
Is there any way at all to do this now? I can't integrate with Auth0 ATM because it calls global.document, which is undefined on the server.

**Comment by delambo** [comment]
I think we could add something like this in kyt. Since we pass the result into `modifyWebpackConfig` with the name `type`, maybe we should use that name for a global variable (`KYT.TYPE`).

For now, you can manually add it inside your kyt.config.js file:

```
const webpack = require('webpack');
module.exports = {
  modifyWebpackConfig: function(config, options) {
    config.plugins.push(
      new webpack.DefinePlugin({
        'process.env.TYPE': options.type,
      })
    );
  },
};
```

Then in your app code you can check if `process.env.TYPE` is "server" or "client".

That code is untested but something like it should work. Let me know if you need any help.

**Comment by janhoogeveen** [comment]
This is working OK enough, but we have one component test failing.  The component is expecting the constant we defined in DefinePlugin to be available but apparently it's not set when running Jest.

**Comment by janhoogeveen** [comment]
Alright, so as a heads up, if you want to use constants from DefinePlugin in your components you will need to add the same constants in your modifyJestConfig as well.

In our case:

```js
  modifyJestConfig: (baseConfig) => {
    // modify baseConfig as needed
    const jestConfig = Object.assign({}, baseConfig);
    // Makes sure we can differentiate between client and server environments
    // in our React codebase
    jestConfig.globals = {
      __CLIENT__: 'false',
      __SERVER__: 'true',
      __PRODUCTION__: 'true',
    };
    return jestConfig;
  },
```

See also: https://facebook.github.io/jest/docs/configuration.html#globals-object
