### ISSUE TITLE
How should I use kyt for a static page?

### ISSUE THREAD

**Issue by ericandrewlewis** [NYTimes/kyt#333]
I'd like to use kyt to serve a static HTML file rather than a node server. Should I use kyt for this?

**Comment by delambo** [comment]
Hey @ericandrewlewis, sorry to get back to you late. We do have a static starter kyt: https://github.com/NYTimes/kyt-starter-static

Let me know if that works for you.

**Comment by ericandrewlewis** [comment]
That is cool, I'll have to try it out.

I wonder if we could set expectations of what comes with the starter kyt, and point people towards the static starter (or other kyts) to suit their desires.
