### ISSUE TITLE
Serve assets from 0.0.0.0:3001 in development

### ISSUE THREAD

**Issue by jaredpalmer** [NYTimes/kyt#346]
### Versions of kyt, node, OS
0.3.0, node 7, macOS Sierra
### Bug or Feature?
Bug
### Current Behavior
Currently impossible to test `react-universal-starter-kyt` on an external browser in development mode. `localhost:3001/main.js` is not made available at `x.x.x.x:3001/main.js`. In production it is served from public directory so a reference to`/main.js` works great. I discovered this only after using safari web inspector on my iPhone. Happy to attach screenshots.
### Desired Behavior
Make webpacked assets available in development over local wifi
### Suggestions
 I think this just means serving up the webpack-dev-server from `0.0.0.0:3001`? I think that should do the trick. After that, should  be able to write a simple ternary expression that replaces`localhost` with `x.x.x.x` for each asset bundle.

**Comment by jaredpalmer** [comment]
NVM, realized i can configure this with `kyt.config.js`

**Comment by hamedty** [comment]
Would you please specify how. The documentation is not that clear! Thanks!
