### ISSUE TITLE
Feature: Use babel-preset-node6 / node7 for server bundle

### ISSUE THREAD

**Issue by c0b** [NYTimes/kyt#356]
since the tool [need NodeJS (v6.0+ required)](https://tom29739.github.io/kyt/#quickstart), I think it makes more sense to build server bundle to babel-preset-node6 or node7, and may give an cli switch to output es5 in server bundle if the user really want that;

Refer https://github.com/NYTimes/kyt/issues/216#issue-181175587

right now my workaround is to use a `modifyWebpackConfig` recipe, but if the option can be default that would be better

```js
modifyWebpackConfig: (baseConfig, options) => {

  if (options.type === 'server') {
    const babelLoader = baseConfig.module.rules.find(
          loader => loader.loader === 'babel-loader');
    babelLoader.options.presets = ['node6', 'react'];
  }

  return baseConfig;
}
```

**Comment by sean-clayton** [comment]
Wouldn't it be best that it goes inside your own `.babelrc` file? No need to modify your webpack config, either.

**Comment by tizmagik** [comment]
Thanks @c0b this actually a good point and we've been discussing this internally for some time. To take this a step further, we're planning on adding support for `babel-preset-env` in #359 -- that, along with kyt 0.4.0 release, which will make babel configuration easier should cover all use cases very cleanly. So I'm going to close this issue for now, but feel free to discuss in those other PRs/issues, or post back here if I missed something. Thanks!

**Comment by c0b** [comment]
@sean-clayton is there a way to use .babelrc to change server build only? please consider add an example in project page or the https://github.com/NYTimes/kyt/tree/master/docs ?
for client build I think it's still preferred to transpile to ES5 for better browser coverage
