### ISSUE TITLE
Missing deploy script

### ISSUE THREAD

**Issue by nahue** [NYTimes/kyt#358]
There should be a way of building a production ready build, say a express server with a route that serves a index.html with all the required assets, i'm willing to contribute if someone points me in the right direction.

**Comment by jaredmcdonald** [comment]
hey @nahue, does [`kyt build`](https://github.com/NYTimes/kyt/blob/master/docs/commands.md#build) not solve your use case? we use that in our internal project to generate production builds.

**Comment by nahue** [comment]
Yes it generates public and server folders, but how can i deploy this? Do i need to use kyt start to run the server in production?

**Comment by ccpricenytimes** [comment]
Hi @nahue,
 `kyt start` is actually just a wrapper for starting your node server.

This is the underlying command that kyt start runs: `node build/server/main.js` which you can use to start up your server when you deploy. 

We're actually going to deprecate `kyt start` in favor of providing the underlying command in v0.4.0. This means you can install kyt as a devDependency in your project.
If you're interested in more details, you can take a look at the [RFC](https://github.com/NYTimes/kyt/issues/323) about this work.

**Comment by delambo** [comment]
@nahue - I'm going to close this. Feel free to open more issues if you have any additional problems.
