### ISSUE TITLE
kyt support/roadmap

### ISSUE THREAD

**Issue by magnusheino** [NYTimes/kyt#364]
Hi.

I am about to start a new project and is currently evaluating kyt, roc and create-react-app.

kyt seems to do everything we want.

What are your thoughts on roadmaps, questions etc? Is this the only forum available for questions/support?

**Comment by delambo** [comment]
Hey, @magnusheino - We've been actively working on the next version of kyt, 0.4.0, which has a lot of interface improvements. You can check out the details [here](https://github.com/NYTimes/kyt/issues/323).

Internally, we are highly invested in kyt. We have a couple of teams using kyt in production and we're getting ready to launch the mobile website and eventually the full www.nytimes.com website on a new architecture that uses kyt. As we battletest these apps in production, we plan on making kyt more opinionated, while keeping it configurable. The two most exciting features that are coming up are [vendor bundling](https://github.com/NYTimes/kyt/issues/315) and service workers.

Github is a good place to reach us so please reach out in issues!

**Comment by delambo** [comment]
Closing this @magnusheino. Things are in motion. We're close to 0.4.0 and I just created a spike for a Service Worker investigation. Thanks for dropping by and let us know if you need any help.

**Comment by magnusheino** [comment]
:thumbsup: Looking forward to the 0.4.0 release.
