### ISSUE TITLE
Make `setup` directory interactive instead of option

### ISSUE THREAD

**Issue by delambo** [NYTimes/kyt#371]
### Versions of kyt, node, OS

0.4.0

### Bug or Feature?

Feature

### Current Behavior

The kyt-cli `setup` command has a `-d`/directory option where a user can specify a directory to create a project.

### Desired Behavior

Since creating a directory is the primary use case when setting up a new kyt project, it might be better to make that option more interactive. We could offer users an interactive option that says, "Enter your project directory name (leave blank to install in the current working directory):"

**Comment by ccpricenytimes** [comment]
Completed in #378
