### ISSUE TITLE
How to load a local JSON file containing routes, but not bundle it?

### ISSUE THREAD

**Issue by rorysmorris** [NYTimes/kyt#375]
Hi there,

I'm fairly new to using React/Node/Express, kyt seemed like a great choice when looking for a base set of files to work from. I'm using the default React starter kyt. 

My job is to take a bunch of JSON that's dumped from a CMS, and turn it into a React site. 

For this to work, I need to be able to populate the 'routes' with data from this JSON file. I've used the code posted below, and this works great. The problem here though, is that my 'import' of the JSON means the data gets compiled into my bundle - which is fine, until the CMS updates the JSON file, at which point the bundle.js doesn't update, rendering it out-of-date (unless I wrote some code to recompile the bundle everytime the CMS updates, which I don't like the sound of).

Can anyone point me in a direction here, please? I've tried a bunch of things, including AJAX/axios requests - but nothing seems to work. I read that Webpack's 'System.import' feature could help me, but I'm lost there too.

/routes/index.js

    import React from 'react';
    import Route from 'react-router/lib/Route';
    import IndexRoute from 'react-router/lib/IndexRoute';

    import App from '../components/App.js';
    import Home from '../components/Home.js';
    import Standard from '../components/Standard.js';
    import Listing from '../components/Listing.js';
    import FourOhFour from '../components/FourOhFour.js';

    import Model from '../app-json/model.json';

    const componentRegistry = {
        "Home": Home,
        "Standard": Standard,
        "Listing": Listing,
        "FourOhFour": FourOhFour
    }

    function buildDynamicRoutes(config){
        var routeJSX = [];

        

            Object.keys(Model.posts).map((key) => {
                var thisComponent = '';
                if(Model.posts[key].template === 'page-listings.php'){
                    thisComponent = 'Listing';
                } else if(Model.posts[key].template === ''){
                    thisComponent = 'Standard';
                }
                routeJSX.push(
                    <Route path={Model.posts[key].route} components={componentRegistry[thisComponent]} key={key} />
                );
            });
            return routeJSX; 

    }

    // Unfortunately, HMR breaks when we dynamically resolve
    // routes so we need to require them here as a workaround.
    // https://github.com/gaearon/react-hot-loader/issues/288
    if (module.hot) {
      require('../components/Home.js');    // eslint-disable-line global-require
      require('../components/Standard.js');   // eslint-disable-line global-require
      require('../components/Listing.js');   // eslint-disable-line global-require
      require('../components/FourOhFour.js');   // eslint-disable-line global-require
    }

    const routes = (
        <Route path="/" component={App}>
            <IndexRoute component={Home} />
            { buildDynamicRoutes() }
            <Route path="*" component={FourOhFour}/>
        </Route>
    );

    export default routes;

**Comment by jaredmcdonald** [comment]
hey @rorysmorris! looks like you'll need to figure out a way to decouple the build from the data. off the cuff, maybe try adding an express route handler that does something like this? see https://expressjs.com/en/api.html#res.sendFile

```js
// server/index.js
app.get('/data.json', ((req, res) => {
  res.sendFile('/path/to/json.json')
})
```

then your client code could make a request to `/data.json` using AJAX or fetch (you might consider using a flux pattern, using something like [redux](http://redux.js.org/), to feed data through your app).

going to close this as it's not an issue with kyt, but hope this helps!

**Comment by samshah007** [comment]
hey @rorysmorris! Are you able to find solution for your query ? I also have same kind of requirement in which I have to load local JSON file into my react component but problem is it's get bundle up into JS file when I build my app for server. That's mean I have to update my JS file every time if I change my JSON file.

**Comment by rorysmorris** [comment]
Hi @samshah007 yes I did find a solution in the end. It was to wrap the routing with an axios call to the JSON file. 

It ended up looking like this:

`// Setup server side routing.
app.get('*', (request, response) => {
    const history = createMemoryHistory(request.originalUrl);

    axios.get('http://localhost:3000/model.json').then(function(data) {
        
        const Model = data.data;
        const routes = buildDynamicRoutes(Model);

        match({ routes, history }, (error, redirectLocation, renderProps) => {
            ...
        });
    });
});`
