### ISSUE TITLE
Keeping project in sync with starter-kyt

### ISSUE THREAD

**Issue by fix-fix** [NYTimes/kyt#385]
### Versions of kyt, node, OS
0.4.0-rc5
### Bug or Feature?
Feature (or even a question)
### Current Behavior
There is no way to update generated project and keep it in sync with starter-kyt after it was set up with `kyt-cli setup`.

Currently starter-kyt can be used only as a starting boilerplate, but what if I want to keep common configs, dependencies, and resources across multiple projects? This way I could specify `my-kyt` as some sort of dependency with its own version and shared resources, and then update common parts in the single place, the same way kyt itself updates now.

Is it recommended for now to use some common `modifyWebpackConfig`/`modifyJestConfig`, eslint and babel presets, that can be defined as dependencies and automatically updated?

### Desired Behavior
Will this kind of feature be supported at some time by kyt?
Is it a good idea or configuration files, such as `package.json`, can't be easily composed from kyt, some starter-kyt, and app itself?

**Comment by delambo** [comment]
Unfortunately, there's no way to do this right now. We've been thinking about that a lot and don't have any good ideas. If you come up with something, let us know please. Thanks @fix-fix
