### ISSUE TITLE
NodeJS source-map using source-map-support

### ISSUE THREAD

**Issue by bkniffler** [NYTimes/kyt#397]
Hey, 
currently source-maps of server main.js are not being used by nodejs. Maybe you guys could try and use https://www.npmjs.com/package/source-map-support to fix that?

**Comment by bkniffler** [comment]
Btw. this can easily be done by adding the following plugin to server config (since it needs to be included in the server entry point):

`new webpack.BannerPlugin('require("source-map-support").install();', {raw: true,entryOnly: false})`

**Comment by delambo** [comment]
Thanks for reporting this @bkniffler. Can you give us an example of what you're fixing here. A pull request would be welcome too.

**Comment by bkniffler** [comment]
If there is an error on the server side, the stack-traces will refer to the compiled main.js file since nodejs is not able to pickup the source map, hence refer the original code. https://www.npmjs.com/package/source-map-support is fixing this.

**Comment by tizmagik** [comment]
The BannerPlugin would put it at the top of every file. Is that what we need or do we just need it at the top of the server entry file? (`{entryOnly: true}`)

**Comment by delambo** [comment]
@bkniffler - I had to use the new one-argument options method and define `banner` to get this to work:
```
new webpack.BannerPlugin({ banner: 'require("source-map-support").install();', raw: true, entryOnly: false }),
```

**Comment by delambo** [comment]
Also, I'm testing this against errors in our internal app and it's not really adding anything. I'm adding `throw 'error'` in random places around the code and I get stack traces with or without this change. What use cases did you find that this addition fixed?

**Comment by delambo** [comment]
@bkniffler - Nevermind. I forgot that we were using `source-map-support` in our internal app so I was able to get a good use case 🙄

**Comment by bkniffler** [comment]
Ah, was just about to file in a testcase ;) Just in case, a `server/index.js` file like this might be enough:

```
import express from 'express';

const app = express();
throw new Error('Test');
app.listen(parseInt(KYT.SERVER_PORT, 10));
```
