### ISSUE TITLE
RFC: Versioning supported starter-kyts with npm

### ISSUE THREAD

**Issue by ccpricenytimes** [NYTimes/kyt#399]
## Summary

We should version and publish supported starter-kyts to npm so they can be kept in sync with their version of kyt and changes can be made to the codebase without breaking starter-kyts.

## Motivation

Since we've moved to a monorepo it would be great to make changes to both kyt and starter-kyts simultaneously (eg. when updating to a new version of webpack) but we currently cannot do this because starter-kyts are installed from the master branch of the code base and kyt is versioned through npm. 

## Detailed design

Supported starter-kyts would be versioned using semver and published to npm. Each starter-kyt would continue to use the "kyt" section of their `package.json` to specify which version(s) of kyt it supports. kyt-cli would download these starter-kyts from npm rather than through git clone. kyt-cli would always download the lastest version of the starter-kyt. 

Rather than cloning the github repo, the `setup` command will npm install the starter-kyt into the temporary directory. From there steup will continue in the same way it currently does. 
Users will still be able to install starter-kyts from other repos using the `-r` flag. This will continue to use git clone.

This will allow us to make changes to the starter-kyt code without breaking any existing setups. 

We will package the starter-kyts in their own package.json so npm install won't install the numerous dependencies but rather can just be used to clone. 

## Drawbacks
This requires versioning the starter-kyts and managing more npm packages. I think the benefits of being able to make changes to the entire monorepo outweighs this. 

## Alternatives
1. We could continue to use github and download the starter-kyts off of some sort of tag system. The problem here is that we would have to figure out how to always pull the latest tag through kyt-cli so we wouldn't have to publish a new version kyt-cli every time a starter-kyt changes.  
3. we can continue with the status quo which requires multiple branchs for changes that affect both kyt and the starter-kyts.

**Comment by janhoogeveen** [comment]
I'm all in favour of versioning both kyt and starter-kyts! I'm working on my own starter-kyt and publishing a package to NPM is something I've never done before but I'm sure I'll manage.

Installing the latest version of a starter-kyt makes sense as a default, although I feel like eventually it would be useful if you can specify which starter-kyt version to install with kyt-cli. Though I suspect that's a very low priority enhancement which I'm not even sure I would use myself.

**Comment by ccpricenytimes** [comment]
Hey @janhoogeveen I think the plan for implementing this would be to just support npm installs for our two starter-kyts in the monorepo. The reason for supporting just that to begin with is it means we can make code changes to kyt-core and those starter-kyts in one branch without potentially breaking starter-kyt installs. 
I think we may eventually want to roll it out for all starter-kyts but I'd like to start smaller to make sure we're not introducing extra friction to the process for little benefit. 

Thanks for your thoughts! 👍

**Comment by janhoogeveen** [comment]
Makes perfect sense. Thanks for the elaborate answer!
