### ISSUE TITLE
Broken links in kyt-cli readme

### ISSUE THREAD

**Issue by scoland** [NYTimes/kyt#404]
The following four links to kyt-starter-universal and kyt-starter-static in the kyt-cli README.md (` kyt/packages/kyt-cli/README.md`) are currently broken:

![firefox_2017-02-19_14-14-46](https://cloud.githubusercontent.com/assets/1489946/23105491/2de3b420-f6ae-11e6-8d8f-87afc1f43ee9.png)

![firefox_2017-02-19_14-18-21](https://cloud.githubusercontent.com/assets/1489946/23105495/4a8aac32-f6ae-11e6-8d4c-0ffd326fdfcc.png)

**Comment by ccpricenytimes** [comment]
Thanks for the heads up @scoland !
