### ISSUE TITLE
Global CSS rules

### ISSUE THREAD

**Issue by AlgoTrader** [NYTimes/kyt#420]
How to load global CSS styles with kyt? 
All the regular css rules are "prefixed/postfixed" like global-container--G--rx".

**Comment by janhoogeveen** [comment]
https://github.com/css-modules/css-modules#exceptions

**Comment by delambo** [comment]
What's your use case @AlgoTrader? In addition to what @janhoogeveen posted, you can include styles for tags. For example, we have a normalize file with a some style definitions for `html`, list items, etc, and when we `import 'normalize.css'` they are added to the stylesheet that CSS Modules produces.

**Comment by AlgoTrader** [comment]
Thanks! I want some layout specific styles and animations to be global, global styles can be referenced without including css into js

**Comment by jaredmcdonald** [comment]
hey @AlgoTrader - gonna close this, feel free to reopen if there are kyt specific changes needed. thanks!
