### ISSUE TITLE
Fix "npm run build" step in Windows ("build" dir is not deleted)

### ISSUE THREAD

**Issue by Skorney** [NYTimes/kyt#430]
I've created PR #429, please take a look.

### Versions of kyt, node, OS
kyt: 0.4.0, node: v7.5.0, windows 10
### Bug or Feature?
Bug
### Current Behavior
The task `npm run build` (`kyt build`) doesn't clean up the build directory.

![11111](https://cloud.githubusercontent.com/assets/206648/23574680/d6e849d8-0035-11e7-866a-137729dbdbfb.png)

### Desired Behavior
The task `npm run build` (`kyt build`) should clean up the build directory on Windows and Linux-based OS.

**Comment by jaredmcdonald** [comment]
this was fixed in #429 and released in [kyt 0.5.0](https://github.com/NYTimes/kyt/blob/master/CHANGELOG.md#050---032317)
