### ISSUE TITLE
Update starter kyts with React Router 4

### ISSUE THREAD

**Issue by delambo** [NYTimes/kyt#442]
Since React Router 4 is officially out we should update the starter kyts. There was some previous discussion around this in #283.

**Comment by TheLordHighExecutioner** [comment]
I notice the Universal React Starter Kyt isn't up-to-date with RR4 (i.e. using Router + browserHistory instead of BrowserRouter). Would I be able to make a quick fix?

**Comment by TheLordHighExecutioner** [comment]
Hey I updated one of the kyts to RR4 

#483

**Comment by janhoogeveen** [comment]
I've worked on this for the universal kyt, but there's one thing I can't get to work. Code splitting. It's even listed at the RR4 documentation as a thing that took them too much time and they didn't solve it yet.

However, I see promising things about using [react-loadable](http://thejameskyle.com/react-loadable.html) in combination with RR4.

See these 2 links specifically:

1. https://twitter.com/matzatorski/status/872059865350406144
2. https://assets.contentful.com/nn534z2fqr9f/1F1M1wNjnicWywOWeUEuSq/17cb533027ee8412616af9f98fa9b0cf/George_Bukhanov_Code_Splitting_with_Server_Side_Rendering.pdf

**Comment by TheLordHighExecutioner** [comment]
Hey, any update to the state of my pr?

#483

**Comment by jcalfee** [comment]
Possible related, code splitting RR4 ticket:
https://github.com/ReactTraining/react-router/issues/4084

**Comment by delambo** [comment]
Closing this for now. More [here](https://github.com/NYTimes/kyt/pull/483#issuecomment-321714410).
