### ISSUE TITLE
Split vendor and main bundles

### ISSUE THREAD

**Issue by janhoogeveen** [NYTimes/kyt#443]
## Summary
Split up the vendor code (React/React DOM/React Router and others) from the application code

## Motivation
Vendor code doesn't change that often, or at least way less than application code. With HTTP2 we're not limited to a certain amount of HTTP connections anymore and it makes sense to keep using vendor assets from cache and only let users download new application code. This will result in smaller bundles and faster downloads/updates.

## Detailed design
Let Webpack automatically split vendor files in another bundle. I saw this blogpost detailing an approach with the CommonChunksPlugin with seems easy enough. https://webpack.js.org/plugins/commons-chunk-plugin/

The hardest part is ensuring all starter-kyts provide an array of vendor files to kyt.config.js. This could be made optional.

## Drawbacks
I don't think there's a reason not to do this. If coded properly the list of vendor files can be optional and won't break anything.

## Alternatives
Not applicable

## Unresolved questions
None from my end

**Comment by jaredmcdonald** [comment]
@janhoogeveen - thanks for this! seems like a potential dupe of @delambo's RFC, #315; we're deliberating on how best to go about this but definitely agree it's something we'd like to see built into kyt core. more soon hopefully!

**Comment by janhoogeveen** [comment]
Oh that's definitely a dupe then! Consider this issue my +1 and we can close it up! 👌🏻
