### ISSUE TITLE
"kyt-cli setup" doesn't work

### ISSUE THREAD

**Issue by jolic** [NYTimes/kyt#455]
### Versions of kyt, node, OS
0.20.3, node 6.8.1, OS X El Capitan
### Bug or Feature?
Bug
### Current Behavior
After starting "kyt-cli setup" it shows
```
0.20.3

🔥  Let's set up your new kyt project...

✨  Answer a few questions to get started  ✨

```

I'm not able to do anything. It hangs...

**Comment by jolic** [comment]
I'm using Oh-My-Zsh: https://github.com/robbyrussell/oh-my-zsh

**Comment by ccpricenytimes** [comment]
Hi @jolic thanks for the heads up. I'll take a look.

**Comment by ccpricenytimes** [comment]
Hi again @jolic which version of kyt-cli are you running?

**Comment by jolic** [comment]
Version is 0.21.3

**Comment by jolic** [comment]
I'm behind a company proxy and ```kyt-cli setup``` works now as you need to add HTTP_PROXY/HTTPS_PROXY! Example:
```HTTP_PROXY=http://YOURPROXY HTTPS_PROXY=https://YOURPROXY kyt-cli setup```

It would be nice if the script shows an error if no connection is available.
Thx

**Comment by ccpricenytimes** [comment]
Glad to hear it's working @jolic 
I'll look into some better error handling on our end.
