### ISSUE TITLE
Incorrect eslint version breaks linting/tests after Airbnb update

### ISSUE THREAD

**Issue by janhoogeveen** [NYTimes/kyt#459]
### Versions of kyt, node, OS
0.5.2

### Bug or Feature?
Bug

### Current Behavior
```
/Users/janhoogeveen/Projects/cleverfranke/kyt-test-15/node_modules/eslint-config-airbnb-base/rules/style.js:
	Configuration for rule "no-restricted-syntax" is invalid:
	Value "[object Object]" is the wrong type.

Referenced from: /Users/janhoogeveen/Projects/cleverfranke/kyt-test-15/node_modules/eslint-config-airbnb-base/index.js
Referenced from: airbnb
```

Also this warning pops up when doing a yarn install
```
warning "eslint-config-airbnb-base@11.1.3" has incorrect peer dependency "eslint@^3.19.0".
```

### Desired Behavior
I'm guessing you'll need to update the peer dependencies of some pacage and update the eslint and eslint plugin importer there.

See https://github.com/airbnb/javascript/issues/1358 and https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb-base

**Comment by ccpricenytimes** [comment]
Hey @janhoogeveen thanks for the heads up I'll take a look today.
