### ISSUE TITLE
How to run on port 80?

### ISSUE THREAD

**Issue by johndavedecano** [NYTimes/kyt#476]
Hi, i see were using port 3000 but how to use port 80 instead?

**Comment by delambo** [comment]
You can add a kyt.config.js file to the root of your project which `module.exports` a configuration with `serverURL` or `clientURL`, including ports, defined with whatever you would like to use. [See more here](https://github.com/NYTimes/kyt/blob/master/docs/kytConfig.md#kytconfigjs-options).

Let me know if this helps.
