### ISSUE TITLE
Update to React Router 4

### ISSUE THREAD

**Issue by TheLordHighExecutioner** [NYTimes/kyt#477]
I noticed that you guys hadn't updated to the new React Router API, so I forked your repository and made some quick fixes. The forked repository passes all the tests.

I'm really new to open-source contributing. What is my next step? Would I be able to submit a pull request?

**Comment by ccpricenytimes** [comment]
Hi @TheLordHighExecutioner ,

Thanks for making that change. Next step would be submitting a PR, then we'll give feedback and merge. 

If you're interested in our contributing guidelines check out [this doc](https://github.com/NYTimes/kyt/blob/master/CONTRIBUTING.md)

Let me know if you have more questions. Going to close this in favor of #442

**Comment by TheLordHighExecutioner** [comment]
Hey, I realized I forgot to add react-router-dom to yarn.lock. Unfortunately, this has been breaking the tests and I've no idea why.

This is what I get if I run "yarn add react-router-dom" to kyt/packages/kyt-starter-static/starter-src/

kyt-starter-static
      ✕ should start a server on :3001 (300066ms)
      ✕ should build (23988ms)

What am I doing wrong?

**Comment by TheLordHighExecutioner** [comment]
Here's some more information on the failure: 

 FAIL  e2e_tests/tests/starter-kyt.test.js (403.607s)
  ● starter kyts › kyt-starter-static › should start a server on :3001

    Timeout - Async callback was not invoked within timeout specified by jasmine.DEFAULT_TIMEOUT_INTERVAL.
      
      at Timeout.callback [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:386:14)
      at tryOnTimeout (timers.js:250:5)
      at Timer.listOnTimeout (timers.js:214:5)

  ● starter kyts › kyt-starter-static › should build

    expect(received).toBe(expected)
    
    Expected value to be (using ===):
      true
    Received:
      false
      
      at Object.it (e2e_tests/tests/starter-kyt.test.js:89:58)
      at Timeout.callback (node_modules/jsdom/lib/jsdom/browser/Window.js:523:19)
      at ontimeout (timers.js:386:14)
      at tryOnTimeout (timers.js:250:5)
      at Timer.listOnTimeout (timers.js:214:5)
