### ISSUE TITLE
Flash of Unstyled Content

### ISSUE THREAD

**Issue by brianboyko** [NYTimes/kyt#478]
### Versions of kyt, node, OS
Kyt: 0.5.2, Node: 7.9, OS: Windows 10.

### Bug or Feature?
Bug.

### Current Behavior
Flash of unstyled content on loading. 

### Desired Behavior
No flash of unstyled content on loading.

**Comment by fix-fix** [comment]
Are your talking about FOUC during dev mode (`npm run dev`)?
Have you tried running production build of the app (`npm run build && npm start`)? Does this fix your problem?

**Comment by jaredmcdonald** [comment]
@fix-fix is right, this is a consequence of how we load styles in the starter-kyts in development mode. in a production build, you shouldn't see any FOUC. closing for now but feel free to reopen if you see this in your prod build 😺
