### ISSUE TITLE
Install and update kyt

### ISSUE THREAD

**Issue by joergklein** [NYTimes/kyt#490]
I install kyt with the command npm install -g kyt-cli. How do I check which Version of kyt is currently used and how do I run an update?

**Comment by jaredmcdonald** [comment]
hey @joergklein, to see what you have installed, you can use [`npm ls`](https://docs.npmjs.com/cli/ls) - so maybe something like:

```bash
npm ls -g --depth=0 | grep kyt-cli
```

adding a `-v` or `--version` flag to `kyt-cli` isn't a bad idea, I'll create an issue for that.

to update it (or any package), use [`npm update`](https://docs.npmjs.com/cli/update)

```bash
npm update -g kyt-cli # will update to latest version
```

**Comment by jaredmcdonald** [comment]
closing in favor of #491, but let me know if you have any other questions :)
