### ISSUE TITLE
Documentation of kyt

### ISSUE THREAD

**Issue by joergklein** [NYTimes/kyt#494]
I am very interested in kyt. Unfortunately there is very little information
or documentation of kyt. I found the website of tom29739.github.io/kyt
#267 and #212. The website looks good, unfortunately little
informative. My suggestion is a github wiki in which details, code snippets,
tips and tricks, as well as a detailed documentation is to be found. Also
could find a manual #324 in the wiki.

**Comment by jaredpalmer** [comment]
What are your specific questions?

**Comment by jaredmcdonald** [comment]
hey @joergklein, going to close this ticket since there isn't really anything actionable, but please let us know in separate issues if you have specific questions. we definitely know that we need a user manual and website, so we'll try to prioritize those soon!
