### ISSUE TITLE
kyt dev occasionally fails to restart

### ISSUE THREAD

**Issue by jaredmcdonald** [NYTimes/kyt#51]
I don't have specific steps for recreating this but occasionally when I'm developing (with `kyt dev`) the server fails to restart, saying the port is already in use:

```
👍  Client build successful
webpack built 7a148d7c5e66a4dae11c in 2544ms
👍  Server build successful
👍  Development server restarted
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::3000
```

killing the process seems to release the port again.

(glancing thru other issues - maybe related to #16?)

**Comment by tizmagik** [comment]
I had this crop up again for me. This time I had some import statement in my app code that was referencing an invalid path, so the initial start the webpack bundle failed to build. I fixed the reference and it restarted the build but then I got `port: 3001 is in use`:

![image](https://cloud.githubusercontent.com/assets/244704/18594323/4d615f58-7c0d-11e6-9096-07997d187928.png)
