### ISSUE TITLE
Instructions to get prettier working are not working when using yarn in 0.7.0 release

### ISSUE THREAD

**Issue by janhoogeveen** [NYTimes/kyt#510]
### Versions of kyt, node, OS
0.7.0, installed with Yarn 0.24.6 on macOS 10.12.5

### Bug or Feature?
Bug.

### Current Behavior
I've upgrated to Kyt 0.7.0 from 0.7.0-rc3. Eager to start using prettier I've removed all of my node_modules, updated kyt-core to 0.7.0 and did a clean install of all modules. I tried to run the specified command:

```bash
$ node_modules/.bin/prettier-eslint src/**/*.js --write
-bash: node_modules/prettier-eslint-cli: No such file or directory
```

Just to make sure it's not my custom starter-kyt that's giving me issues I've set up a new project based on the universal starter kyt. Same results there.

This command however, does give me something:
```bash
$ node_modules/prettier-eslint-cli/dist/index.js src/**/*.js --write
5 files were unchanged
```

In my package.json I had an NPM command that did work which looked like this, for what it's worth:

```git
-    "prettier": "kyt lint-script -- --fix",
+    "prettier": "node_modules/.bin/prettier-eslint src/**/*.js --write",
```

### Desired Behavior
Prettier working out of the box!

**Comment by delambo** [comment]
Hey @janhoogeveen - Thanks for the report 🙏  I did some testing and it looks like this is some kind of hoisting problem with yarn. When I installed a starter kyt and 0.7.0 into our internal project with npm the `prettier-eslint` worked properly.

As a workaround right now, you can temporarily install `prettier-eslint` into your project or use npm. I highly recommend reverting back to using npm. In the latest 5.1.0 release, npm now has comparable speeds to yarn and a lot of bugs fixed. We're going to switch to npm and remove yarn support in kyt at some point. yarn should go the way of io.js.

**Comment by janhoogeveen** [comment]
I'll test it with NPM and let you know how that works out. No point in installing prettier-eslint manually if you're going to drop yarn support eventually! :)

**Comment by delambo** [comment]
@janhoogeveen - heads up - npm 5.2.0 broke kyt. They're reverting the change, but if you upgrade npm you will probably want to use 5.1.0 for now: `npm i npm@5.1.0 -g`

**Comment by janhoogeveen** [comment]
I'm at 5.3.0 and everything seems to work fine so far!
