### ISSUE TITLE
Remove yarn support

### ISSUE THREAD

**Issue by delambo** [NYTimes/kyt#511]
Modern versions of npm support lock files and have comparable speeds to yarn. Also, yarn has a different api and implementation as we saw in #510. We should move kyt off of yarn and only support npm.

### Current Behavior

Currently, kyt-cli supports yarn and npm, and the kyt development process relies on yarn.

### Desired Behavior

Remove yarn support and recommend npm 5.0+.

**Comment by Jasu** [comment]
Hi,

We use yarn for it's support for [workspaces](https://yarnpkg.com/blog/2017/08/02/introducing-workspaces/) and [resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/). I don't think NPM has either.

**Comment by delambo** [comment]
Thanks for the info @Jasu. I think we can close this now. I removed yarn from our bootstrap process, and I think it's ok to leave support for users in the CLI.
