### ISSUE TITLE
Missing support for Webpack resolve.root or resolve.moduleDirectories

### ISSUE THREAD

**Issue by 0x80** [NYTimes/kyt#513]
I am used to configuring webpack to resolve modules in my `src` directory. I can do this in two ways; using `baseConfig.resolve.root` or `baseConfig.resolve.moduleDirectories`. Both don't seem to be supported by the Kyt config validator. What's the idea behind that? 

```
{ WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.resolve has an unknown property 'root'. These properties are valid:
   object { alias?, aliasFields?, cachePredicate?, descriptionFiles?, enforceExtension?, enforceModuleExtension?, extensions?, fileSystem?, mainFields?, mainFiles?, moduleExtensions?, modules?, plugins?, resolver?, symlinks?, unsafeCache?, useSyncFileSystemCalls? }
```

**Comment by tizmagik** [comment]
These options were replaced (deprecated in webpack2, dropped in webpack 3) with resolve.modules[] -- https://webpack.js.org/guides/migrating/#resolve-root-resolve-fallback-resolve-modulesdirectories

**Comment by 0x80** [comment]
Oops. I didn't realize Kyt already moved on from webpack v1 😅 

Thanks 👍

**Comment by bvn13** [comment]
> These options were replaced (deprecated in webpack2, dropped in webpack 3) with resolve.modules[] -- https://webpack.js.org/guides/migrating/#resolve-root-resolve-fallback-resolve-modulesdirectories

link is dead, sadly
