### ISSUE TITLE
VSCode stylelint extension breaks because of outdated rule config 

### ISSUE THREAD

**Issue by 0x80** [NYTimes/kyt#516]
The vscode stylelint extension is broken. Reporting the error: `stylelint: Undefined rule selector-no-id`

I tried running stylelint v7 myself on the `stylelint-config-kyt` and it gives this output:

```
Deprecation Warning: 'selector-no-id' has been deprecated and in 8.0 will be removed. Instead use 'selector-max-id' with '0' as its primary option. See: https://stylelint.io/user-guide/rules/selector-no-id/
```

So I figure the vscode extension is already at stylelint v8 and therefor unable to handle this configuration. 

I'm surprised that this config is so outdated, if v7 gives a polite deprecation warning.

**Comment by 0x80** [comment]
https://github.com/NYTimes/kyt/pull/517

**Comment by delambo** [comment]
[This has been fixed](https://github.com/NYTimes/kyt/blob/master/CHANGELOG.md#100-alpha1-102017). Please test on your end and report back if it is still broken. Thanks for bringing up the issue.

**Comment by 0x80** [comment]
👍  I am not involved in any projects using Kyt anymore however, so I won't be verifying this.
