### ISSUE TITLE
Webpack Common Shake

### ISSUE THREAD

**Issue by tizmagik** [nytimes/kyt#520]
## What
Use [webpack-common-shake](https://github.com/indutny/webpack-common-shake)

## Why
For CommonJS tree-shaking

## Expected outcome
PR that adds it, or an exploration around why it might not be a good idea

**Comment by staylor** [comment]
has not been updated in 2 years / Webpack v4 era - I doubt this is needed?

**Comment by tizmagik** [comment]
:long-drag: I think you're right
