### ISSUE TITLE
Missing stack traces

### ISSUE THREAD

**Issue by jcalfee** [NYTimes/kyt#523]
I caused this error below, but the issue is that I don't see a stack trace.  Every time I'm missing stack traces when I have an error in a component so naturally some errors can be hard to find.

```bash
> 1.0.0 start
> node build/server/main.js

✅  Started development on port: 3000
(node:6488) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'props' of undefined
(node:6488) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Versions of kyt, node, OS
kyt 0.7.0 node v8.2.1 ubuntu 16.04
plugins: 'transform-decorators-legacy', 'transform-class-properties'
kyt.config.js is unedited
Happens under `npm start` and `npm run dev` .. 

### Bug or Feature?
Bug

### Current Behavior
Server: An error in the component becomes an unhanded promise rejection (no info other than error.message)

Client: Just hangs, no feedback

### Desired Behavior
Need to see a stack trace.

**Comment by jcalfee** [comment]
Some errors occur only in the browser and those are giving a stack trace.  Looks like it is the server code that is not catching the promise.

**Comment by delambo** [comment]
Hey @jcalfee - You may need some more guards/catches in your Promises. See this for [more](http://jamesknelson.com/are-es6-promises-swallowing-your-errors/). We added an exception handler in `server/index.js` for this case:

```
process.on('unhandledRejection', err => {
  console.error(err.stack);
});
```

Let me know if that works for you. Maybe we should add that to the universal starter kyt.

**Comment by ccpricenytimes** [comment]
Going to close this. Please reopen if you're still seeing issues.

**Comment by jcalfee** [comment]
Awesome .. thanks I'll check it out.
