### ISSUE TITLE
Add numbers to setup prompts

### ISSUE THREAD

**Issue by freking** [NYTimes/kyt#536]
### Versions of kyt, node, OS
 Git Bash (Git Version 2.7.0), Windows 10

### Bug or Feature?
Feature
### Current Behavior
kyt-cli setup uses arrow keys to make selections during setup. Currently there is a bug in Git Bash and other Windows Bash implementations which cause the arrow keys to not work. As a work around you can type a number and then hit enter to make a selection.  So when prompted to select Yarn or npm as seen below... 
```
$ kyt-cli setup
0.22.0

🔥  Let's set up your new kyt project...

✨  Answer a few questions to get started  ✨

? Choose an installer (Use arrow keys)
> yarn
  npm
```

 I type "2" and then hit enter and npm is selected.   

### Desired Behavior
Add a number to the beginning of each of the choices so it is obvious that you are able to use the number keys as a substitute for the arrow keys.  Alternatively this workaround could be included in the documentation.

**Comment by freking** [comment]
After thinking about this issue I have decided to close this issue.  I think most users who run into this issue would just use the CMD terminal not spend a half hour trying to fix the arrow keys like I did.

**Comment by delambo** [comment]
Sorry about your trouble, @freking!
