### ISSUE TITLE
Server side rendering broken?

### ISSUE THREAD

**Issue by schoenberger** [nytimes/kyt#547]
### Versions of kyt, node, OS

kyt 0.9.0, ky-cli 0.2.1, node 8.4.0, ubuntu 16.04.2

### Bug or Feature?

Bug

### Current Behavior

Correct me if I'm wrong, but I think server side rendering is broken.
To be more specific, server side rendering works but the client always re-renders (so you would not need server-side-rendering at all).

### Desired Behavior

The client should not re-render components.

### Steps to reproduce

 - create a new universal app
 - in browser debug React's `_mountImageIntoNode` function (i.e. chrome dev tools, sources tab, line 432 in `webpack://./node_modules/react/lib/ReactMount.js`)
 - the variable `shouldReuseMarkup` is false, so React always re-renders the components
 - this can be fixed by removing the inner `div` [here](https://github.com/NYTimes/kyt/blob/v0.9.0/packages/kyt-starter-universal/starter-src/src/server/template.js#L27)
 - but now there are differences and React shows a warning (in dev environment)
 - the root-cause is react-router, but the problem (and a fix) is mentioned in the [docs](https://github.com/ReactTraining/react-router/blob/v2.6.1/docs/guides/ServerRendering.md#async-routes)

I've created a working example [here](https://github.com/schoenberger/univeral-kyt-0.9.0-fix/commit/4c898fa446d643ab82892e140d7b9ce80b73bb19) - don't know if it fits your style...

**Comment by staylor** [comment]
this is probably a relic of `ReactDOM.render()`, which blows away the DOM tree, where `ReactDOM.hydrate()` does not: https://github.com/nytimes/kyt/blob/master/packages/kyt-starter-universal/starter-src/src/client/index.js#L7
