### ISSUE TITLE
scss import doesnt apply style

### ISSUE THREAD

**Issue by Irfanbsse2060** [NYTimes/kyt#552]
I am importing scss file in a component. but it doesnt apply .  I have to reference it on each element.
For example
import style from "./componentStyle.scss"

`<div className={style["book-cover"]}> </div>`

 i dont want to do extra thing.It should apply on the component when i import it.please help me out.how can i do it?

**Comment by thomaspaillot** [comment]
This is the expected behavior as css module is enable by default you need to reference the class name on each element. If you want to disable this functionality you'll need to modify the webpack config through kit config file (kyt.config.js).

**Comment by Irfanbsse2060** [comment]
@thomaspaillot thanks for reply. yes you are right i need to modify webpack file using kyt config file. do you know which configuration do i need to set exactly?

**Comment by thomaspaillot** [comment]
See this issue #243 for a way to disbale css modules or you can try to use this code:
```javascript
modifyWebpackConfig: baseConfig => {
    const rules = baseConfig.module.rules;

    const cssRule = rules.find(rule => String(rule.test) === String(/\.css$/));
    Reflect.deleteProperty(cssRule, 'loader');
    cssRule.use = ['style-loader', 'css-loader'];

    const scssRule = rules.find(rule => String(rule.test) === String(/\.scss$/));
    Reflect.deleteProperty(scssRule, 'loader');
    scssRule.use = ['style-loader', 'css-loader', 'sass-loader'];

    return baseConfig;
}
```

**Comment by delambo** [comment]
@Irfanbsse2060 - let me know if you still need help with this - sorry for jumping in so late
