### ISSUE TITLE
Update react-router to the latest version (React Router 4)

### ISSUE THREAD

**Issue by erchaves** [nytimes/kyt#559]
# RFC: Update react-router to the latest version (React Router 4)

## Summary
[summary]: #summary

React Router is an important part of the react ecosystem. KYT currently uses a significantly older version of react router. In order to keep KYT up to date and compatible with future development, this RFC proposes that we update to react router 4.

## Motivation
[motivation]: #motivation

Rect router 4 is significantly different from older versions. I think react 4 is better and simpler to understand. As demonstrated in the corresponding PR, I believe it also fixes issues that otherwise had to work around, like this [react-hot-loader issue](https://github.com/NYTimes/kyt/blob/9fd7212d2e9edde6c37ac083e1c5491a113bb2de/packages/kyt-starter-universal/starter-src/src/routes/index.js#L38).

## Detailed design
[design]: #detailed-design

This PR upgrades react-router 2.6.1 with react-router-dom 4.2.2. React-router-dom is just the flavor of react-router with DOM bindings, and corresponds to react-router 4.2.X.

The PR only focuses on the kyt-starter-universal package for now, but these changes could be propagated to other packages as needed.

Other files changed include:
`client/Root.js`
`client/index.js`
`components/App/index.js`
`routes/index.js`
`server/index.js`

The server side code in `server/index.js` is updated to follow the [recommended approach](https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/StaticRouter.md) for matching routes in react router 4. 

## Drawbacks
[drawbacks]: #drawbacks

While I have already done the work of making these updates and running the tests, this will take a little work from the team to vet this update and make sure it's compatible with all the packages.
## Alternatives
[alternatives]: #alternatives

We could leave the react-router version as is. The downside is that KYT could start to feel out-of-date as future developers will be accustomed to the newer react router format. They could be potentially confused by the old react router api.

## Unresolved questions
[unresolved]: #unresolved-questions

- The update to react-router 4 in the universal package probably needs to be propagated to the other packages.
- This PR removed some code-splitting related code in routes/index.js which seemed unnecessary. I'm not sure if that is still necessary and desired and should be added back in.

**Comment by erchaves** [comment]
As mentioned in the unresolved questions, I'm not sure if this change is compatible with code-splitting. This article is a good reference for how we could maybe implement automatic code-splitting with react router 4. https://serverless-stack.com/chapters/code-splitting-in-create-react-app.html

I haven't tried this approach yet. Before I investigate further, I'll wait to see if this RFC generates interest.

**Comment by staylor** [comment]
as of this writing, `5.2.0`: https://github.com/nytimes/kyt/blob/master/packages/kyt-starter-universal/starter-src/package.json#L37
