### ISSUE TITLE
Can't access the development server from the local network

### ISSUE THREAD

**Issue by nathanvogel** [nytimes/kyt#588]
Hi, 

I'm trying to access the dev server from the local network (to debug from my phone), currently the only way I've found to do so it to set `clientURL` to my current local IP, which isn't practical.

### Versions of kyt, node, OS
Kyt 0.9.0
Node v10.9.0
macOS 10.14.3

### Bug or Feature?
Bug / question

### Current Behavior
When setting clientURL to "http://0.0.0.0:3001", I can load the HTML from another device via "http://XXX.XXX.XXX.XXX:3001", but main.js won't load and gives this error in the console: 
```
"Failed to load resource: net::ERR_CONNECTION_REFUSED" 
```
So the app basically doesn't work. The same thing happens over ngrok. This is the relevant part of my `kyt.config.js`:
```
module.exports = {
  reactHotLoader: true,
  clientURL: "http://0.0.0.0:3001",
  debug: false,
  hasServer: false,
...
```

### Desired Behavior
The server is accessible from the local network.

Is there a recommended way to achieve this?

**Comment by drazisil** [comment]
`0.0.0.0` Is not an IP. It tells a server to listen on all IP addresses it has access to.

You will need to set it to `xxx.xxx.xxx.xxx`

**Comment by woodb** [comment]
Thanks @drazisil, that is correct! @nathanvogel you can try maybe to make your life easier on your local network by setting some kind of DNS solution there to resolve consistently to your local machine to other devices on the network.

Closing this as invalid.
