### ISSUE TITLE
JS filenames are not matching between publicAssets.json and build folder

### ISSUE THREAD

**Issue by eewang** [nytimes/kyt#596]
Hi there! 

I'm a newbie kyt user, so forgive me if this issue is more user error than kyt bug, but I'm not able to deploy my kyt-based app to Heroku. After some digging, it seems that the mapped client JS filenames in `build/publicAssets.json` are not matching the actual filenames in `build/public`.

### Versions of kyt, node, OS
kyt version: 0.9.0
node: 8.8.1
OS: OSX 10.14.3 (Mojave)

### Bug or Feature?
Bug

### Current Behavior
I'm deploying a kyt app to Heroku, and I'm seeing a mismatch between the asset fingerprints on the `*.js` files and the `*.js.map` files in my `build/public` directory after the build process completes, causing the client JS assets to fail on load (returns 404) when I try to go to my app in the browser. Moreover, the `build/publicAssets.json` file is referring to the correct `*.js.map` file but the incorrect `*.js` file.

Here's an example of what it looks like:

*build/publicAssets.json*

```
{
  "main.js": "/main-51c97afcab028412c1cb.js",
  "main.js.map": "/main-51c97afcab028412c1cb.js.map",
  "vendor.js": "/vendor-99c3dc38de78e09a714e.js",
  "vendor.js.map": "/vendor-99c3dc38de78e09a714e.js.map"
}
```
*filenames in ./build/public folder`*

```
main-51c97afcab028412c1cb.js.map
main-b689ce8285397833b7ae.js
vendor-99c3dc38de78e09a714e.js.map
vendor-cca730aea893dab94c40.js
```

Note that on the server, the `*.js` and `*.js.map` filenames have different fingerprints, and that the `publicAssets.json` file is assuming that the `*.js` file takes on the filename of the `*.js.map` file.

Looks like this just affects my JS files; the CSS files load fine, as the `*.css` and `*.css.map` files share the same root filename and fingerprint.

### Temporary Fix
I was able to fix this in a hacky manner by disabling the client asset fingerprinting process in the `modifyWebpackConfig` callback, like so:

```
  modifyWebpackConfig: (baseConfig, options) => {
    const path = baseConfig.output.path;

    if (path.split("/").filter(d => d).pop() == "public") {
      const config = baseConfig.output;
      config.chunkFilename = '[name].js';
      config.filename = '[name].js'
      baseConfig.output = config;
    }
    return baseConfig;
  }
```

This causes my deployed assets to not have a hash suffix, so that the `publicAssets.json` dictionary maps to the correct asset filenames in `build/public`, thus enabling my client-side JS app to load properly. However, this is clearly less than ideal since I can't leverage asset caching in the same way, so it'd be great to re-enable asset fingerprinting.

### Desired Behavior
My client-side JS app works properly when deployed to Heroku with client asset fingerprinting enabled.

**Comment by trangtv04110** [comment]
I have the same Issue

**Comment by esonderegger** [comment]
I ran into this issue today attempting to upgrade a project from kyt 0.4.0 to 0.9.0. It looks like it was fixed in https://github.com/nytimes/kyt/pull/578.

Would it be possible to tag a release sometime after that fix and publish it to npm?

**Comment by staylor** [comment]
this has long since been deployed
