### ISSUE TITLE
npm run dev error

### ISSUE THREAD

**Issue by ork821** [nytimes/kyt#606]
### Versions of kyt, node, OS
Node: 10.16.3 LTS
OS: MacOC Mojave

### Bug or Feature?
Bug

### Current Behavior
Error causes when starting server

### Desired Behavior
Test behavior of installation and starting server
The issue on the line 72, webpack.base.js
Paste this: fs.writeFileSync(assetsFilePath, JSON.stringify(assets, null, ' '), 'utf8');
It solves problem

**Comment by staylor** [comment]
the generation of this path has since moved to `kyt-utils/paths`: https://github.com/nytimes/kyt/blob/master/packages/kyt-utils/src/paths.js#L16
