### ISSUE TITLE
Extend kyt's local linters when setting up eslint and stylelint

### ISSUE THREAD

**Issue by delambo** [NYTimes/kyt#91]
The way kyt handles linter configurations isn't ideal. Currently, on `setup`, we drop the linter rc's into the user's root directory so the user can extend them and use them in editor plugins. Since the linters are no longer packaged, kyt has no way to update those files. 

To work around this, I propose we separately package the linter configurations inside of kyt and push them up to npm. That way, on `setup`, we can continue giving user's extensible linter rc's, but also gain the ability to update rules and dependencies in future releases.

Thoughts?

**Comment by delambo** [comment]
Re-opening this. Per our discussion: Instead of creating new packages, the default liter files should use `extends` to link to the `node_modules/kyt/...lintfile`

**Comment by tizmagik** [comment]
Should be able to:

```
  "extends": [
    "airbnb",
    "./node_modules/kyt/.eslintrc"
  ]
```

Or something along those lines :)
